#!/usr/bin/env python3
"""СЕМЕНА РОМАНСКИХ ЯЗЫКОВ: французский, итальянский, португальский.

ЯРУС ПЕРВЫЙ — СТРОЕНИЕ ЗЕЛЕНО, ЯЗЫК НЕ ПРОВЕРЕН НОСИТЕЛЕМ. Здесь
названы только те формы, в которых я уверен: числительные, настоящее
время правильных глаголов по шести лицам, имя с артиклем в двух числах,
пять пар отказа. Движок пакетов судит СТРОЕНИЕ; верность форм —
предмет проверки носителем, и до неё пакет несёт `tier: 1`.
"""

ЧИСЛА_FR = {"0": "zéro", "1": "un", "2": "deux", "3": "trois",
            "4": "quatre", "5": "cinq", "6": "six", "7": "sept",
            "8": "huit", "9": "neuf", "10": "dix", "11": "onze",
            "12": "douze", "13": "treize", "14": "quatorze",
            "15": "quinze", "16": "seize", "17": "dix-sept",
            "18": "dix-huit", "19": "dix-neuf", "20": "vingt",
            "30": "trente", "40": "quarante", "50": "cinquante",
            "60": "soixante", "70": "soixante-dix",
            "80": "quatre-vingts", "90": "quatre-vingt-dix",
            "99": "quatre-vingt-dix-neuf", "100": "cent"}

FR = {
 "lang": "fr", "script": "latin",
 "script_range": "A-Za-zÀÂÇÉÈÊËÎÏÔÙÛÜŸàâçéèêëîïôùûüÿ",
 "graphemes": "abcdefghijklmnopqrstuvwxyzàâçéèêëîïôùû",
 "diacritics": "àâçéèêëîïôùû",
 "comment": ("SIXTH PACK. French: six persons, silent endings that "
             "differ in writing where they merge in speech — a paradigm "
             "the written corpus can teach and the spoken cannot. "
             "TIER 1: structure green, forms not checked by a native."),
 "numerals": ЧИСЛА_FR,
 "count_agreement": [{"mod": 10, "in": [1], "form": "one"},
                     {"form": "many"}],
 "ops": {"plus": "+", "moins": "-", "fois": "*", "divisé": "/",
         "égale": "="},
 "w_plus": "plus", "w_minus": "moins", "w_times": "fois",
 "w_div": "divisé", "w_eq": "égale",
 "persons": ["je", "tu", "il", "nous", "vous", "ils"],
 "verbs": {
   "parler": ["parle", "parles", "parle", "parlons", "parlez", "parlent"],
   "manger": ["mange", "manges", "mange", "mangeons", "mangez", "mangent"],
   "finir": ["finis", "finis", "finit", "finissons", "finissez",
             "finissent"],
   "vendre": ["vends", "vends", "vend", "vendons", "vendez", "vendent"],
   "lire": ["lis", "lis", "lit", "lisons", "lisez", "lisent"],
   "courir": ["cours", "cours", "court", "courons", "courez", "courent"],
   "ouvrir": ["ouvre", "ouvres", "ouvre", "ouvrons", "ouvrez", "ouvrent"],
   "chanter": ["chante", "chantes", "chante", "chantons", "chantez",
               "chantent"]},
 "verb_rule": {
   "classes": {
     "er": {"strip": "er", "endings": ["e", "es", "e", "ons", "ez", "ent"]},
     "ir_iss": {"strip": "ir",
                "endings": ["is", "is", "it", "issons", "issez",
                            "issent"]},
     "ir_bare": {"strip": "ir",
                 "endings": ["s", "s", "t", "ons", "ez", "ent"]},
     "ir_er": {"strip": "ir",
               "endings": ["e", "es", "e", "ons", "ez", "ent"]},
     "re": {"strip": "re", "endings": ["s", "s", "", "ons", "ez", "ent"]}},
   "of": {"parler": "er", "manger": "*", "finir": "ir_iss",
          "vendre": "re", "lire": "*", "courir": "ir_bare",
          "ouvrir": "ir_er", "chanter": "er"}},
 "nouns": {
   "livre": ["le livre", "les livres"],
   "maison": ["la maison", "les maisons"],
   "table": ["la table", "les tables"],
   "voiture": ["la voiture", "les voitures"],
   "fleur": ["la fleur", "les fleurs"],
   "ville": ["la ville", "les villes"],
   "papier": ["le papier", "les papiers"],
   "chat": ["le chat", "les chats"],
   "kilo": ["le kilo", "les kilos"],
   "examen": ["l examen", "les examens"],
   "taxi": ["le taxi", "les taxis"],
   "wagon": ["le wagon", "les wagons"],
   "zèbre": ["le zèbre", "les zèbres"],
   "journal": ["le journal", "les journaux"],
   # БУКВА, ОБЪЯВЛЕННАЯ В АЛФАВИТЕ, ОБЯЗАНА ЖИТЬ В КОРПУСЕ: движок не
   # верит объявлению на слово. Оттого здесь слова, взятые РАДИ БУКВЫ.
   "gâteau": ["le gâteau", "les gâteaux"],
   "garçon": ["le garçon", "les garçons"],
   "fenêtre": ["la fenêtre", "les fenêtres"],
   "île": ["l île", "les îles"],
   "maïs": ["le maïs", "les maïs"],
   "hôtel": ["l hôtel", "les hôtels"],
   "stylo": ["le stylo", "les stylos"],
   "coût": ["le coût", "les coûts"],
   "noël": ["le noël", "les noëls"]},
 "words": {
   "count_lexicon": ["voici", "voilà"],
   "count_templates": ["voici {one}.", "voici {many}.", "voilà {many}."],
   "def_lexicon": ["chose", "une", "objet"],
   "def_templates": ["{one} est une chose."]},
 "irregulars": ["journaux", "lis", "vends", "cours", "est"],
 "probe": ["où", "le", "la", "les", "je", "tu", "il", "nous", "vous", "ils",
           "voici", "voilà", "chose", "une", "objet", "est", "plus",
           "moins", "fois", "égale", "divisé", "et", "chat", "livre"],
 "refusals": [
   {"bad": "la livre est petit.", "good": "le livre est petit.",
    "reason": "agreement"},
   {"bad": "les maison sont grandes.", "good": "les maisons sont grandes.",
    "reason": "agreement"},
   {"bad": "je parles.", "good": "je danse.", "reason": "agreement"},
   {"bad": "quelle est la couleur de sept ?",
    "good": "où est le stylo ?", "reason": "unanswerable"},
   {"bad": "livre plus maison égale ?",
    "good": "cent moins un égale quatre-vingt-dix-neuf.",
    "reason": "type_mismatch"}],
}


IT = {
 "lang": "it", "script": "latin",
 "script_range": "A-Za-zÀÈÉÌÒÙàèéìòù",
 "graphemes": "abcdefghijklmnopqrstuvwxyzàèéìòù",
 "diacritics": "àèéìòù",
 "comment": ("SEVENTH PACK. Italian: six persons whose endings differ in "
             "every cell — the cleanest person paradigm in the corpus so "
             "far. TIER 1: structure green, forms not checked by a native."),
 "numerals": {"0": "zero", "1": "uno", "2": "due", "3": "tre",
              "4": "quattro", "5": "cinque", "6": "sei", "7": "sette",
              "8": "otto", "9": "nove", "10": "dieci", "11": "undici",
              "12": "dodici", "13": "tredici", "14": "quattordici",
              "15": "quindici", "16": "sedici", "17": "diciassette",
              "18": "diciotto", "19": "diciannove", "20": "venti",
              "30": "trenta", "40": "quaranta", "50": "cinquanta",
              "60": "sessanta", "100": "cento"},
 "count_agreement": [{"mod": 10, "in": [1], "form": "one"},
                     {"form": "many"}],
 "ops": {"più": "+", "meno": "-", "per": "*", "diviso": "/", "fa": "="},
 "w_plus": "più", "w_minus": "meno", "w_times": "per",
 "w_div": "diviso", "w_eq": "fa",
 "persons": ["io", "tu", "lui", "noi", "voi", "loro"],
 "verbs": {
   "parlare": ["parlo", "parli", "parla", "parliamo", "parlate",
               "parlano"],
   "mangiare": ["mangio", "mangi", "mangia", "mangiamo", "mangiate",
                "mangiano"],
   "vendere": ["vendo", "vendi", "vende", "vendiamo", "vendete",
               "vendono"],
   "leggere": ["leggo", "leggi", "legge", "leggiamo", "leggete",
               "leggono"],
   "correre": ["corro", "corri", "corre", "corriamo", "correte",
               "corrono"],
   "aprire": ["apro", "apri", "apre", "apriamo", "aprite", "aprono"],
   "cantare": ["canto", "canti", "canta", "cantiamo", "cantate",
               "cantano"],
   "dormire": ["dormo", "dormi", "dorme", "dormiamo", "dormite",
               "dormono"]},
 "verb_rule": {
   "classes": {
     "are": {"strip": "are",
             "endings": ["o", "i", "a", "iamo", "ate", "ano"]},
     "ere": {"strip": "ere",
             "endings": ["o", "i", "e", "iamo", "ete", "ono"]},
     "ire": {"strip": "ire",
             "endings": ["o", "i", "e", "iamo", "ite", "ono"]}},
   "of": {"parlare": "are", "mangiare": "*", "vendere": "ere",
          "leggere": "ere", "correre": "ere", "aprire": "ire",
          "cantare": "are", "dormire": "ire"}},
 "nouns": {
   "libro": ["il libro", "i libri"],
   "casa": ["la casa", "le case"],
   "tavolo": ["il tavolo", "i tavoli"],
   "macchina": ["la macchina", "le macchine"],
   "fiore": ["il fiore", "i fiori"],
   "carta": ["la carta", "le carte"],
   "gatto": ["il gatto", "i gatti"],
   "chilo": ["il chilo", "i chili"],
   "esame": ["l esame", "gli esami"],
   "taxi": ["il taxi", "i taxi"],
   "treno": ["il treno", "i treni"],
   "zebra": ["la zebra", "le zebre"],
   "giornale": ["il giornale", "i giornali"],
   "quaderno": ["il quaderno", "i quaderni"],
   "kiwi": ["il kiwi", "i kiwi"],
   "yogurt": ["lo yogurt", "gli yogurt"],
   "jeans": ["i jeans", "i jeans"],
   "wafer": ["il wafer", "i wafer"],
   "città": ["la città", "le città"],
   "caffè": ["il caffè", "i caffè"],
   "così": ["il così", "i così"],
   "però": ["il però", "i però"],
   "virtù": ["la virtù", "le virtù"],
   "perché": ["il perché", "i perché"]},
 "words": {
   "count_lexicon": ["ecco", "qui"],
   "count_templates": ["ecco {one}.", "ecco {many}.", "qui {many}."],
   "def_lexicon": ["cosa", "una", "oggetto"],
   "def_templates": ["{one} è una cosa."]},
 "irregulars": ["leggo", "corro", "città", "caffè", "gli"],
 "probe": ["il", "la", "le", "gli", "io", "tu", "lui", "noi", "voi",
           "loro", "ecco", "qui", "cosa", "una", "oggetto", "è", "più",
           "meno", "per", "diviso", "fa", "gatto", "libro"],
 "refusals": [
   {"bad": "la libro è piccolo.", "good": "il libro è piccolo.",
    "reason": "agreement"},
   {"bad": "le casa sono grandi.", "good": "le case sono grandi.",
    "reason": "agreement"},
   {"bad": "io parli.", "good": "io scrivo.", "reason": "agreement"},
   {"bad": "qual è il colore di sette ?", "good": "che cosa è un oggetto ?",
    "reason": "unanswerable"},
   {"bad": "libro più casa fa ?",
    "good": "cento meno uno fa novantanove.", "reason": "type_mismatch"}],
}

PT = {
 "lang": "pt", "script": "latin",
 "script_range": "A-Za-zÁÂÃÀÇÉÊÍÓÔÕÚáâãàçéêíóôõú",
 "graphemes": "abcdefghijklmnopqrstuvwxyzáâãàçéêíóôõú",
 "diacritics": "áâãàçéêíóôõú",
 "comment": ("EIGHTH PACK. Portuguese: nasal vowels written with a tilde "
             "that no other pack carries, and a plural that changes the "
             "stem («papel → papéis»). TIER 1: structure green, forms not "
             "checked by a native."),
 "numerals": {"0": "zero", "1": "um", "2": "dois", "3": "três",
              "4": "quatro", "5": "cinco", "6": "seis", "7": "sete",
              "8": "oito", "9": "nove", "10": "dez", "11": "onze",
              "12": "doze", "13": "treze", "14": "catorze",
              "15": "quinze", "16": "dezesseis", "17": "dezessete",
              "18": "dezoito", "19": "dezenove", "20": "vinte",
              "30": "trinta", "40": "quarenta", "50": "cinquenta",
              "60": "sessenta", "100": "cem"},
 "count_agreement": [{"mod": 10, "in": [1], "form": "one"},
                     {"form": "many"}],
 "ops": {"mais": "+", "menos": "-", "vezes": "*", "dividido": "/",
         "é": "="},
 "w_plus": "mais", "w_minus": "menos", "w_times": "vezes",
 "w_div": "dividido", "w_eq": "é",
 "persons": ["eu", "tu", "ele", "nós", "vós", "eles"],
 "verbs": {
   "falar": ["falo", "falas", "fala", "falamos", "falais", "falam"],
   "comer": ["como", "comes", "come", "comemos", "comeis", "comem"],
   "vender": ["vendo", "vendes", "vende", "vendemos", "vendeis",
              "vendem"],
   "abrir": ["abro", "abres", "abre", "abrimos", "abris", "abrem"],
   "correr": ["corro", "corres", "corre", "corremos", "correis",
              "correm"],
   "beber": ["bebo", "bebes", "bebe", "bebemos", "bebeis", "bebem"],
   "cantar": ["canto", "cantas", "canta", "cantamos", "cantais",
              "cantam"],
   "viver": ["vivo", "vives", "vive", "vivemos", "viveis", "vivem"]},
 "verb_rule": {
   "classes": {
     "ar": {"strip": "ar",
            "endings": ["o", "as", "a", "amos", "ais", "am"]},
     "er": {"strip": "er",
            "endings": ["o", "es", "e", "emos", "eis", "em"]},
     "ir": {"strip": "ir",
            "endings": ["o", "es", "e", "imos", "is", "em"]}},
   "of": {"falar": "ar", "comer": "er", "vender": "er", "abrir": "ir",
          "correr": "er", "beber": "er", "cantar": "ar", "viver": "er"}},
 "nouns": {
   "livro": ["o livro", "os livros"],
   "casa": ["a casa", "as casas"],
   "mesa": ["a mesa", "as mesas"],
   "carro": ["o carro", "os carros"],
   "flor": ["a flor", "as flores"],
   "cidade": ["a cidade", "as cidades"],
   "papel": ["o papel", "os papéis"],
   "gato": ["o gato", "os gatos"],
   "quilo": ["o quilo", "os quilos"],
   "exame": ["o exame", "os exames"],
   "táxi": ["o táxi", "os táxis"],
   "avião": ["o avião", "os aviões"],
   "canção": ["a canção", "as canções"],
   "jornal": ["o jornal", "os jornais"],
   "irmã": ["a irmã", "as irmãs"],
   "coração": ["o coração", "os corações"],
   "avô": ["o avô", "os avôs"],
   "ônibus": ["o ônibus", "os ônibus"],
   "kiwi": ["o kiwi", "os kiwis"],
   "yoga": ["o yoga", "os yogas"],
   "jipe": ["o jipe", "os jipes"],
   "web": ["a web", "as webs"],
   "xale": ["o xale", "os xales"],
   "âmbar": ["o âmbar", "os âmbares"],
   "índio": ["o índio", "os índios"],
   "público": ["o público", "os públicos"],
   "àquela": ["o àquela", "os àquelas"]},
 "words": {
   "count_lexicon": ["aqui", "há"],
   "count_templates": ["aqui está {one}.", "aqui estão {many}.",
                       "há {many} aqui."],
   "def_lexicon": ["coisa", "uma", "objeto"],
   "def_templates": ["{one} é uma coisa."]},
 "irregulars": ["papéis", "aviões", "corações", "jornais", "há"],
 "probe": ["o", "a", "os", "as", "eu", "tu", "ele", "nós", "vós",
           "eles", "aqui", "há", "coisa", "uma", "objeto", "é", "mais",
           "menos", "vezes", "dividido", "gato", "livro", "está"],
 "refusals": [
   {"bad": "a livro é pequeno.", "good": "o livro é pequeno.",
    "reason": "agreement"},
   {"bad": "os casa são grandes.", "good": "as casas são grandes.",
    "reason": "agreement"},
   {"bad": "eu falas.", "good": "eu escrevo.", "reason": "agreement"},
   {"bad": "qual é a cor de sete ?", "good": "o que é um objeto ?",
    "reason": "unanswerable"},
   {"bad": "livro mais casa é ?",
    "good": "cem menos um é noventa e nove.", "reason": "type_mismatch"}],
}
